# Generated by Django 5.2 on 2025-04-09 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('meditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meditation')),
                ('retreat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.retreat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'meditation')},
            },
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
